# The instructions for the first stage
FROM node:13.1.0-alpine as builder

WORKDIR /usr/src/app

ENV NODE_ENV=development

COPY bcrypt-dependencies.sh ./
RUN ./bcrypt-dependencies.sh

COPY setup-puppeteer-dependencies.sh ./
RUN ./setup-puppeteer-dependencies.sh

COPY package.json ./
COPY yarn.lock ./

RUN yarn install

COPY . .

CMD [ "yarn", "start" ]
