version: '3'
services:
  app-dev:
    environment:
    - PORT=5000
    - MONGODB_URL=mongodb://mongo:27017/users-dev
    - SESSION_SECRET=secret!
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    links:
    - mongo
  app-prod:
    environment:
    - PORT=3000
    - MONGODB_URL=mongodb://mongo:27017/users
    - SESSION_SECRET=secret!
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    links:
    - mongo
  mongo:
    image: mongo:4.2.1
    ports:
    - "27017:27017"
    volumes:
    - mongoData:/data/db
volumes:
  mongoData: {}
